# SPDX-License-Identifier: GPL-3.0-or-later
# Library= là tên KHÔNG kèm ".so" — Fcitx5 tự thêm đuôi (vd libclipboard → libclipboard.so).
[Addon]
Name=TextVN
Comment=Vietnamese Input Method Engine for Fcitx5 (Telex, VNI, VIQR)
Category=InputMethod
Type=SharedLibrary
OnDemand=True
Configurable=False
Library=libtextvn-fcitx5

[Addon/Dependencies]
0=core
