# SPDX-License-Identifier: GPL-3.0-or-later
[package]
name = "vietime-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "textvn-cli"
path = "src/main.rs"

[dependencies]
vietime-ffi = { path = "../ffi" }
vietime-config = { path = "../config" }

[target.'cfg(windows)'.dependencies]
windows-core = "0.61"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_UI_TextServices",
] }
