# SPDX-License-Identifier: GPL-3.0-or-later
[Addon]
Name=TextVN
Comment=Vietnamese Input Method Engine (Telex, VNI, VIQR)
Category=InputMethod
Type=SharedLibrary
OnDemand=True
Configurable=True
Library=libtextvn-fcitx5.so

[Addon/Dependencies]
0=core

[InputMethod/textvn]
Name=TextVN
Icon=textvn_v
LangCode=vi
Label=VN
Priority=1
